# Generated by Django 4.1.7 on 2023-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('reportedBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('staff', 'Staff')], default='', max_length=200)),
            ],
        ),
    ]
