# Generated by Django 4.1.7 on 2023-09-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('staff', 'Staff')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
