# Generated by Django 4.1.7 on 2023-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=200)),
                ('orgType', models.CharField(max_length=200)),
            ],
        ),
    ]
