# Generated by Django 4.1.7 on 2023-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_delete_laptop_user_type_alter_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serviceType', models.CharField(max_length=100)),
                ('serviceDesc', models.TextField(max_length=500)),
            ],
        ),
    ]
