# Generated by Django 4.1.7 on 2023-09-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_orgtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgType',
            new_name='OrgUser',
        ),
    ]
